descriptor-schema-version: "2.7"
info:
  name: iox-aarch64-persistdata
  version: latest
app:
  cpuarch: arm64
  env:
    DEBIAN_FRONTEND: noninteractive
    HOME: /root
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    TERM: xterm
  resources:
    cpu: "400"
    memory: "128"
    network:
    - interface-name: eth0
      ports: {}
    profile: custom
    host_mounts:
      -
        host_mount_path: "/bootflash/SHARED-IOX"
        target_mount: "/mnt/SHARED-IOX"
        description: "used for store and forward"
  startup:
    rootfs: rootfs.tar
    target:
    - bash
    - /idle.sh
    workdir: /root
  type: docker
